const express = require('express')
const router = express.Router()

const checkAdmin = require('../middlewares/admin_check.js')
const signin = require('./signin.js')
const main = require('./main.js')
const saveCurse = require('./save_curse.js')
const changeCurse = require('./change_curse.js')
const loadOtherCurses = require('./load_other_curses.js')
const changeAdminPassword = require('./change_admin_password.js')
const admin = require('./admin.js')
const deleteCurse = require('./delete_curse.js')
const addAdmin = require('./add_admin.js')
const deleteAdmin = require('./delete_admin.js')
const changeAdmin = require('./change_admin.js')
const saveQuestion = require('./save_question.js')
const getQuestions = require('./get_questions.js')

router.get('/', main)
router.post('/signin', signin)
router.post('/saveCurse', checkAdmin, saveCurse)
router.post('/changeCurse', checkAdmin, changeCurse)
router.post('/deleteCurse', checkAdmin, deleteCurse)
router.get('/loadOtherCurses', loadOtherCurses)
router.post('/changeAdminPassword', checkAdmin, changeAdminPassword)
router.get('/admin', admin)
router.post('/addAdmin', checkAdmin, addAdmin)
router.post('/deleteAdmin', checkAdmin, deleteAdmin)
router.post('/changeAdmin', checkAdmin, changeAdmin)
router.post('/saveQuestion', checkAdmin, saveQuestion)
router.get('/getQuestions', getQuestions)

module.exports = router